/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed": "#373f54",
              "inverse-surface": "#0b0f10",
              "tertiary-container": "#d2d9f8",
              "on-tertiary-fixed": "#323951",
              "on-tertiary-fixed-variant": "#4e556f",
              "on-secondary-container": "#4a5167",
              "surface-container-high": "#e1e9ee",
              "secondary-dim": "#4b5369",
              "on-background": "#2a3439",
              "primary-fixed": "#e2dfff",
              "primary-container": "#e2dfff",
              "on-error-container": "#782232",
              "secondary": "#575f75",
              "inverse-primary": "#8582ff",
              "surface-container-low": "#f0f4f7",
              "inverse-on-surface": "#9a9d9f",
              "outline": "#717c82",
              "surface-dim": "#cfdce3",
              "error-dim": "#4f0116",
              "primary-dim": "#4034d7",
              "primary": "#4d44e3",
              "surface-tint": "#4d44e3",
              "on-secondary-fixed-variant": "#535b71",
              "surface-container-lowest": "#ffffff",
              "background": "#f7f9fb",
              "tertiary": "#575e78",
              "surface-variant": "#d9e4ea",
              "on-primary-fixed-variant": "#4a40e0",
              "surface": "#f7f9fb",
              "on-surface-variant": "#566166",
              "on-surface": "#2a3439",
              "error-container": "#ff8b9a",
              "on-error": "#fff7f7",
              "secondary-container": "#dae2fd",
              "on-secondary": "#f9f8ff",
              "on-primary-fixed": "#2a13c5",
              "surface-bright": "#f7f9fb",
              "surface-container-highest": "#d9e4ea",
              "tertiary-dim": "#4b526c",
              "error": "#9e3f4e",
              "tertiary-fixed-dim": "#c4cbe9",
              "on-primary": "#faf6ff",
              "outline-variant": "#a9b4b9",
              "primary-fixed-dim": "#d2d0ff",
              "secondary-fixed-dim": "#ccd4ee",
              "on-primary-container": "#3f33d6",
              "tertiary-fixed": "#d2d9f8",
              "surface-container": "#e8eff3",
              "on-tertiary-container": "#444c65",
              "on-tertiary": "#faf8ff",
              "secondary-fixed": "#dae2fd"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Inter", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
