apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devboard-api
  template:
    metadata:
      labels:
        app: devboard-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting for db; sleep 2; done;",
            ]

      containers:
        - name: api
          image: ghcr.io/saurabhkumargit/devboard:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: postgresql://user:password@postgres-service:5432/devboard
            - name: REDIS_URL
              value: redis://redis-service:6379
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m" 