name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

# ✅ force future GitHub runtime (Node 24)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint || echo "No lint configured"

  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: devboard
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      DATABASE_URL: postgres://user:password@localhost:5432/devboard
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - run: npx prisma generate
      - run: npx prisma migrate deploy

      - run: npm test || echo "No tests yet"

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v5

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/saurabhkumargit/devboard:latest \
            -t ghcr.io/saurabhkumargit/devboard:${{ github.sha }} \
            .

      - name: Push image
        run: |
          docker push ghcr.io/saurabhkumargit/devboard:latest
          docker push ghcr.io/saurabhkumargit/devboard:${{ github.sha }}